---
# defaults file for initial

hostname: project-name.local
packages: [
  git-core,
  curl,
  wget,
  htop,
  python-psycopg2,
  libpq-dev,
  unzip,
  zip,
  expect-dev,
  mc
]

busy_disk_space_limit: 75 # Percent of busy space after which clean up will be triggered